### PR TITLE
Release/v1.9.0 helper functions

### PR DESCRIPTION
**Pull request by dustinbleile**
Release v1.9.0
New Features:
 - get_statements_from_variants - helper function added.
 - get_term_list - helper function added.
 - get_rid - helper function added.
 - get_pharmacogenomic_info - helper function added.
 - get_cancer_predisposition_info - helper function added.
 - Added constants PHARMACOGENOMIC_RELEVANCE_TERMS and PHARMACOGENOMIC_SOURCE_EXCLUDE_LIST
Bugfix:
 - Ignore gene name version in get_equivalent_features. Eg. NM_033360.4 should match 'NM_033360' and 'KRAS'.
Improvements:
 - get_preferred_gene_name - moved to genes.py
 - move CHOMOSOMES and PREFERRED_GENE_SOURCE to constants.py
 - added tests:
   - test_get_pharmacogenomic_info
   - test_get_cancer_predisposition_info
Github Workflow Updates:
 - Drop Python 3.6 testing
 - actions/checkout@v3
 - actions/setup-python@v3

### CODE REVIEW

**Comment by mattdoug604** [comment]
Removing python 3.6 from the actions seems to have helped, but now some of the tests are failing because they can't connect to GraphKB? https://github.com/bcgsc/pori_graphkb_python/actions/runs/3661691735/jobs/6333814847#step:7:2852

**Comment by dustinbleile** [comment]
Hi @creisle,
Could you update the actions here as well to omit python 3.6 from the expected build?

Like you did here:
https://github.com/bcgsc/pori_ipr_python/pull/102#issuecomment-1386191419

**Comment by dustinbleile** [comment]
This doesn't seem to be working.

So many tests have been disabled, we will just fail the code coverage.

Hi @creisle, can we just turn off all these requirements for checks until someone can figure out why they are failing?

Hi @mattdoug604  or @elewis2 does anyone else have any idea what going on here?

**Comment by creisle** [comment]
> This doesn't seem to be working.
> 
> So many tests have been disabled, we will just fail the code coverage.
> 
> Hi @creisle, can we just turn off all these requirements for checks until someone can figure out why they are failing?
> 
> Hi @mattdoug604 or @elewis2 does anyone else have any idea what going on here?

I think it would be dangerous to just allow the lower coverage. It would be better to wait to fix the tests if at all possible

**Comment by dustinbleile** [comment]
All these tests actually run, just not on github.

Why is everything either running in under a minute or 'timing out' after 0.5 - 4 hours on github?

**Comment by creisle** [comment]
> All these tests actually run, just not on github.
> 
> Why is everything either running in under a minute or 'timing out' after 0.5 - 4 hours on github?

I suspect its to do with the external api (in this case to graphkb) calls. If so can see 2 solutions for this. 

1. Mock the API calls with stored JSON data files (downside is this loses all the integration aspect of the testing)
2. Make a testdb docker version of the graphkb db we can use for testing and spin that up during the tests (this is the better overall solution but will take a bit more work to load everything)

**Comment by dustinbleile** [comment]
Closing this PR.

Will pull in @elewis2's fixes for the workflow checks from develop and make a new PR for Release v1.9.0

**Pull request closed without merging**
